#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Custom Planet Example
# ═══════════════════════════════════════════════════════════════════════════════
# This is an example of how to create a custom planet for Vibe Palace.
# Copy this file and customize it for your needs.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# Get planet script directory
PLANET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source core libraries
source "$PLANET_DIR/../lib/core.sh"
source "$PLANET_DIR/../lib/state.sh"

# ═══════════════════════════════════════════════════════════════════════════════
# PLANET METADATA
# ═══════════════════════════════════════════════════════════════════════════════

PLANET_NAME="mycustom"
PLANET_VERSION="1.0.0"
PLANET_DESC="My custom planet with my favorite tools"

# ═══════════════════════════════════════════════════════════════════════════════
# REQUIRED FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

# planet_metadata: Return information about this planet
planet_metadata() {
    cat <<EOF
{
  "name": "$PLANET_NAME",
  "version": "$PLANET_VERSION",
  "description": "$PLANET_DESC",
  "duration": "5 min"
}
EOF
}

# planet_dependencies: Declare dependencies on other planets
planet_dependencies() {
    # Add dependencies here, one per line
    # echo "mercury"  # If you need terminal tools
    # echo "venus"    # If you need editors
    # echo "mars"     # If you need languages

    # For example, if your planet needs terminal tools:
    echo "mercury"
}

# planet_install: Main installation logic
planet_install() {
    step "Installing $PLANET_NAME..."

    # Check if already installed
    if planet_is_installed; then
        log "Already installed, skipping..."
        return 0
    fi

    # Detect OS
    local os
    os=$(detect_os)
    log "Installing on $os..."

    # Install tools based on OS
    case "$os" in
        linux)
            # Linux installation logic
            log "Installing tools on Linux..."

            # Example: Install a tool using brew
            if command_exists brew; then
                brew install example-tool
            else
                error "Homebrew not found. Please install it first."
                return 1
            fi

            # Example: Install using cargo
            # cargo install example-rust-tool

            # Example: Install using npm
            # npm install -g example-node-tool

            # Example: Install using Python pip
            # pip install example-python-tool

            ;;
        macos)
            # macOS installation logic
            log "Installing tools on macOS..."

            if command_exists brew; then
                brew install example-tool
            else
                error "Homebrew not found. Please install it first."
                return 1
            fi

            ;;
        *)
            error "Unsupported OS: $os"
            return 1
            ;;
    esac

    # Create configuration directory
    local config_dir="$HOME/.config/$PLANET_NAME"
    mkdir -p "$config_dir"

    # Create configuration file
    cat > "$config_dir/config" <<EOF
# $PLANET_NAME configuration
# Generated by Vibe Palace

# Add your custom configuration here
setting=value
EOF

    # Verify installation
    if ! planet_check_health 2>/dev/null; then
        error "Installation verification failed"
        return 1
    fi

    # Update state
    state_add "$PLANET_NAME" "$PLANET_VERSION"

    success "$PLANET_NAME installed successfully!"
    return 0
}

# planet_uninstall: Remove the planet
planet_uninstall() {
    step "Uninstalling $PLANET_NAME..."

    # Remove binaries (example)
    if command_exists example-tool; then
        log "Removing example-tool..."

        case "$(detect_os)" in
            linux|macos)
                if command_exists brew; then
                    brew uninstall example-tool
                fi
                ;;
        esac
    fi

    # Remove configurations
    local config_dir="$HOME/.config/$PLANET_NAME"
    if [[ -d "$config_dir" ]]; then
        log "Removing configurations..."
        rm -rf "$config_dir"
    fi

    # Update state
    state_remove "$PLANET_NAME"

    success "$PLANET_NAME uninstalled!"
    return 0
}

# planet_check_health: Verify installation is healthy
planet_check_health() {
    step "Checking $PLANET_NAME health..."

    local failed=0

    # Check if binary exists
    if ! command_exists example-tool; then
        error "example-tool not found in PATH"
        ((failed++))
    fi

    # Check if configuration exists
    if [[ ! -f "$HOME/.config/$PLANET_NAME/config" ]]; then
        warn "Configuration file not found"
        ((failed++))
    fi

    # Check if tool works
    if command_exists example-tool; then
        if ! example-tool --version &>/dev/null; then
            error "example-tool not functioning correctly"
            ((failed++))
        fi
    fi

    if [[ $failed -eq 0 ]]; then
        success "$PLANET_NAME is healthy!"
        return 0
    else
        error "$PLANET_NAME has $failed health issue(s)"
        return 1
    fi
}

# planet_is_installed: Check if already installed
planet_is_installed() {
    # Check for key indicators of installation
    command_exists example-tool && \
    [[ -f "$HOME/.config/$PLANET_NAME/config" ]]
}

# ═══════════════════════════════════════════════════════════════════════════════
# OPTIONAL: Custom functions (not called by vibe, but can be useful)
# ═══════════════════════════════════════════════════════════════════════════════

# custom_function_example() {
#     log "This is a custom helper function"
# }

# ═══════════════════════════════════════════════════════════════════════════════
# USAGE
# ═══════════════════════════════════════════════════════════════════════════════
#
# To use this custom planet:
#
# 1. Copy this file to your planets directory:
#    cp examples/custom-planet.sh planets/mycustom.sh
#
# 2. Edit planets/mycustom.sh and customize:
#    - Change PLANET_NAME, PLANET_VERSION, PLANET_DESC
#    - Add your installation logic in planet_install()
#    - Add your uninstallation logic in planet_uninstall()
#    - Add your health checks in planet_check_health()
#    - Update planet_is_installed() to check for your tools
#
# 3. Test your planet:
#    ./vibe install mycustom
#
# 4. If it works, share it!
#    - Submit a PR to Vibe Palace
#    - Or keep it in your custom planets directory
#
# ═══════════════════════════════════════════════════════════════════════════════
